.PHONY: default
default: build

.PHONY: build
build:
	g++ -Wall -Wextra -O2 -fwrapv -Wfloat-equal -Wconversion -std=c++17 contest.cpp -o contest

.PHONY: run
run:
	g++ -Wall -Wextra -O2 -fwrapv -Wfloat-equal -Wconversion -std=c++17 contest.cpp -o contest && ./contest